# Base image:
FROM ruby:2.3.3

MAINTAINER MD MASUD RANA "masudcsesust04@gmail.com"

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

# Create a directory where the rails app is installed inside of Docker image:
ENV RAILS_ROOT /rails-boot-starter
RUN mkdir -p $RAILS_ROOT

# Set working directory, where the command will be ran:
WORKDIR $RAILS_ROOT

# Add Gmefile and Gemfile.lock to the working direcotry
ADD Gemfile $RAILS_ROOT/Gemfile
ADD Gemfile.lock $RAILS_ROOT/Gemfile.lock

# Install bundler gem
RUN gem install bundler

# Install gems
RUN bundle install --jobs 20 --retry 5 --without test

# Add current directory to the application directory to the Docker image
ADD . $RAILS_ROOT
