copy_file 'spec/controllers/home_controller_spec.rb'
copy_file 'spec/factories/users_factory.rb'
copy_file 'spec/models/user_spec.rb'
copy_file 'spec/rails_helper.rb'
copy_file 'spec/routes/routes_spec.rb'
copy_file 'spec/spec_helper.rb'
copy_file 'spec/support/factory_girl.rb'
